## 1. default 변수에 다음 3개의 변수를 작성하세요.
## mariadb_version: 10.1 
## mariadb_databases (값 없음)
## mariadb_users (값 없음)

## 2. tasks에 다음 작업을 작성하세요

## 2-1. mariadb 레포지토리를 작성하세요
## yum_repository 모듈을 사용하여 아래의 argument를 작성하세요
## baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64"
## gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

## 2-2. yum 모듈을 사용하여 패키지를 설치하세요
## MariaDB-server, MariaDB-client, MariaDB-devel, MySQL-python

## 2-3 service 모듈을 사용하여 mariadb 활성화 하세요

## 2-4 mysql_db 모듈을 사용하여 DB를 생성하세요
## db명은 mariadb_databases 변수를 사용하여 설정하세요
## encoding: "{{ item.encoding|default('utf8') }}"
## collation: "{{ item.collation|default('utf8_general_ci') }}"

## 2-5 mysql_user 모듈을 사용하여 사용자를 생성하세요
## name, password, priv argument를 지정하고 host 는 localhost로 작성하세요
## argument에는 mariadb_users 변수를 사용하세요
