## 1. default 변수로 다음을 작성하세요
## php_fpm_php_version: 7.0
## php_fpm_additional_packages (값 없음)

## 2. var 변수로 다음을 작성하세요
## php_fpm_config_dir: /etc/php-fpm.d

## 3. service 모듈로 php-fpm 을 재시작하는 handler 를 작성하세요

## 4. tasks 에 다음 작업을 작성하세요

## 4-1 yum_repository 모듈을 사용하여 centos 레포지토리를 만드세요
## baseurl: http://ftp.daum.net/centos/7/os/$basearch/
## gpgcheck: no

## 4-2 epel 레포지토리를 설치하세요
## yum 모듈을 사용하여 다음 rpm 을 설치하세요
## http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

## 4-3 Remi 레포지토리를 설치하세요
## yum 모듈을 사용하여 다음 rpm 을 설치하세요
## https://rpms.remirepo.net/enterprise/remi-release-7.rpm

## 4-4 php-fpm 패키지를 설치하세요
## enalberepo argument를 사용하여 다음을 지정하세요
## "remi-php{{ php_fpm_php_version|replace('.', '') }}"
## php-fpm, php-devel, php-enchant, php-mbstring, php-process, php-xml, php-gd, {{ php_fpm_additional_packages }}
## notify 를 사용하여 3번 항목에서 지정된 핸들러를 호출하세요

## 4-5 service 모듈로 php-fpm 을 재기동하세요
